apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::517542309828:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-KCM3HfqJRAfv
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::517542309828:user/roy
      username: roy 
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-04T16:20:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1196"
  uid: c87bab60-ea75-4bf4-8c6e-a437581bab3d